### PR TITLE
Fix History REST API

### PR DESCRIPTION
**Pull request by trams**
Use attempts/xxx to access attempt info in Hadoop 2.6
I do not have currently older Hadoop version to check

### CODE REVIEW

**Comment by toidi** [comment]
Hey @trams 
Thank you for the PR.

Fix tests and I'll merge it.

**Comment by xiaop1987** [comment]
@trams  you tests failed because of the environment issue, i fixed in another [PR](https://github.com/toidi/hadoop-yarn-api-python-client/pull/4), you can checkout the changes after @toidi merge my PR.

**Comment by trams** [comment]
Thank you so much!

2016-07-08 9:49 GMT+02:00 Tianjin Gu <notifications@github.com>:

> @trams <https://github.com/trams> you tests failed because of the
> environment issue, i fixed in another PR
> <https://github.com/toidi/hadoop-yarn-api-python-client/pull/4>, you can
> checkout the changes after @toidi <https://github.com/toidi> merge my PR.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/toidi/hadoop-yarn-api-python-client/pull/5#issuecomment-231297173>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAOdPH9ru9KH6G_myqAdvxIupjpiMm7sks5qTgD3gaJpZM4JFkgT>
> .
>



-- 
Kind regards,
Oleksandr Pryimak

**Comment by toidi** [comment]
@trams please rebase master to fix tests

**Comment by trams** [comment]
I am sorry. I was a bit carried away by another project. I rebased

**Pull request merged**
